import { StyleSheet } from 'react-native';

export const PRIMARY = '#2563eb';
export const INK = '#101828';
export const MUTED = '#667085';
export const SURFACE = '#ffffff';
export const SOFT = '#f5f7fb';
export const BORDER = '#e4e7ec';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: SOFT,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  topBar: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 26,
    padding: 14,
    marginBottom: 16,
    boxShadow: '0 18px 45px rgba(16,24,40,0.08)',
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoMark: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  brandTitle: {
    color: INK,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  brandSub: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '600',
  },
  topActions: {
    position: 'absolute',
    right: 12,
    top: 14,
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    minWidth: 52,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#eef4ff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  iconButtonText: {
    color: PRIMARY,
    fontWeight: '800',
    fontSize: 12,
  },
  welcome: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 12,
  },
  hero: {
    backgroundColor: INK,
    borderRadius: 32,
    padding: 26,
    minHeight: 360,
    justifyContent: 'flex-end',
    marginBottom: 28,
    boxShadow: '0 24px 60px rgba(16,24,40,0.18)',
  },
  eyebrow: {
    color: PRIMARY,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 40,
    lineHeight: 44,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 14,
  },
  heroText: {
    color: '#d0d5dd',
    fontSize: 17,
    lineHeight: 25,
    fontWeight: '600',
    marginBottom: 22,
  },
  heroActions: {
    gap: 10,
  },
  sectionHeader: {
    marginBottom: 14,
    marginTop: 6,
  },
  sectionTitle: {
    color: INK,
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: MUTED,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 4,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 26,
  },
  categoryCard: {
    width: '47%',
    backgroundColor: SURFACE,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 16,
    minHeight: 108,
    justifyContent: 'space-between',
  },
  categoryTitle: {
    color: INK,
    fontSize: 17,
    fontWeight: '900',
  },
  categoryText: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '600',
  },
  ctaCard: {
    backgroundColor: '#eef4ff',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#c7d7fe',
    padding: 22,
    marginTop: 14,
  },
  ctaTitle: {
    color: INK,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 8,
  },
  ctaText: {
    color: MUTED,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 16,
  },
  pageIntro: {
    marginBottom: 16,
  },
  pageTitle: {
    color: INK,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
    letterSpacing: 0,
  },
  pageText: {
    color: MUTED,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 8,
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 15,
    fontSize: 16,
    color: INK,
    marginBottom: 12,
  },
  filtersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  filterChip: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  filterChipText: {
    color: INK,
    fontWeight: '800',
    fontSize: 13,
  },
  professionalCard: {
    backgroundColor: SURFACE,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: BORDER,
    marginBottom: 16,
    overflow: 'hidden',
    boxShadow: '0 16px 38px rgba(16,24,40,0.08)',
  },
  cardImage: {
    height: 150,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImageFill: {
    width: '100%',
    height: '100%',
  },
  cardImageText: {
    color: PRIMARY,
    fontSize: 18,
    fontWeight: '900',
  },
  cardContent: {
    padding: 18,
    gap: 9,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  professionalName: {
    color: INK,
    fontSize: 18,
    fontWeight: '900',
    flex: 1,
  },
  professionalRole: {
    color: PRIMARY,
    fontSize: 16,
    fontWeight: '900',
  },
  bodyText: {
    color: MUTED,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '600',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  metaText: {
    color: '#475467',
    fontSize: 13,
    fontWeight: '800',
  },
  availability: {
    color: '#067647',
    fontSize: 13,
    fontWeight: '900',
  },
  authCard: {
    backgroundColor: SURFACE,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 22,
    boxShadow: '0 18px 45px rgba(16,24,40,0.08)',
  },
  card: {
    backgroundColor: SURFACE,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 18,
    marginBottom: 14,
  },
  cardTitle: {
    color: INK,
    fontSize: 21,
    fontWeight: '900',
    letterSpacing: 0,
  },
  cardSubtitle: {
    color: MUTED,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  formStack: {
    marginTop: 18,
    gap: 14,
  },
  fieldGroup: {
    gap: 7,
  },
  label: {
    color: INK,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 14,
    color: INK,
    fontSize: 16,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: PRIMARY,
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    boxShadow: '0 14px 30px rgba(37,99,235,0.25)',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
  ghostButton: {
    backgroundColor: '#fff',
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: BORDER,
  },
  ghostButtonText: {
    color: INK,
    fontSize: 16,
    fontWeight: '900',
  },
  disabled: {
    opacity: 0.55,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  segmented: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segment: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#f2f4f7',
    borderWidth: 1,
    borderColor: BORDER,
  },
  segmentActive: {
    backgroundColor: INK,
    borderColor: INK,
  },
  segmentText: {
    color: MUTED,
    fontWeight: '900',
    fontSize: 13,
  },
  segmentTextActive: {
    color: '#fff',
  },
  badge: {
    backgroundColor: '#eef4ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: PRIMARY,
    fontSize: 12,
    fontWeight: '900',
  },
  profileHero: {
    backgroundColor: INK,
    borderRadius: 32,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
  },
  avatarLarge: {
    width: 96,
    height: 96,
    borderRadius: 34,
    backgroundColor: '#eef4ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  avatarText: {
    color: PRIMARY,
    fontSize: 30,
    fontWeight: '900',
  },
  profileName: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  profileRole: {
    color: '#d0d5dd',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  pricePanel: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    padding: 16,
    marginTop: 14,
  },
  priceLabel: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '800',
  },
  priceText: {
    color: INK,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  dashboardHero: {
    backgroundColor: '#fff',
    borderRadius: 30,
    padding: 22,
    borderWidth: 1,
    borderColor: BORDER,
    marginBottom: 14,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: INK,
    borderRadius: 22,
    padding: 16,
    minHeight: 104,
    justifyContent: 'space-between',
  },
  statValue: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
  },
  statLabel: {
    color: '#d0d5dd',
    fontSize: 12,
    fontWeight: '800',
  },
  actionGrid: {
    gap: 12,
  },
  actionCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 24,
    padding: 18,
    gap: 8,
  },
  linkText: {
    color: PRIMARY,
    fontSize: 14,
    fontWeight: '900',
  },
  notice: {
    backgroundColor: '#fffaeb',
    borderWidth: 1,
    borderColor: '#fedf89',
    borderRadius: 18,
    padding: 13,
    marginBottom: 12,
  },
  noticeText: {
    color: '#93370d',
    fontWeight: '800',
    lineHeight: 20,
  },
  loadingPill: {
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingText: {
    color: MUTED,
    fontWeight: '800',
  },
  emptyState: {
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 22,
    alignItems: 'center',
  },
  emptyTitle: {
    color: INK,
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 6,
  },
  emptyText: {
    color: MUTED,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  tipBox: {
    backgroundColor: '#eef4ff',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#c7d7fe',
  },
  tipBoxMuted: {
    backgroundColor: '#f9fafb',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: BORDER,
  },
  tipTitle: {
    color: INK,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 4,
  },
  tipText: {
    color: MUTED,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
});
