import { StyleSheet } from 'react-native';

export const palette = {
  primary: '#2457ff',
  primaryDark: '#172554',
  secondary: '#14b8a6',
  accent: '#f97316',
  success: '#079455',
  warning: '#dc6803',
  error: '#d92d20',
  background: '#f6f8fc',
  surface: '#ffffff',
  surfaceAlt: '#eef4ff',
  border: '#d9e2f1',
  text: '#111827',
  textSecondary: '#667085',
  textMuted: '#98a2b3',
  white: '#ffffff',
};

export const PRIMARY = palette.primary;
export const INK = palette.text;
export const MUTED = palette.textSecondary;
export const SURFACE = palette.surface;
export const SOFT = palette.background;
export const BORDER = palette.border;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 40,
};

const shadowSoft = {
  boxShadow: '0 14px 34px rgba(15, 23, 42, 0.08)',
};

const shadowMedium = {
  boxShadow: '0 18px 50px rgba(15, 23, 42, 0.14)',
};

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: palette.background,
  },
  scroll: {
    flex: 1,
  },
  screenBody: {
    flex: 1,
    paddingHorizontal: spacing.md,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  appHeader: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: palette.background,
  },
  headerCard: {
    minHeight: 72,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(217,226,241,0.9)',
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    ...shadowSoft,
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerGreeting: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  topBar: {
    minHeight: 72,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(217,226,241,0.9)',
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadowSoft,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoMark: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: palette.primaryDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '900',
  },
  brandTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  brandSub: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  topActions: {
    position: 'absolute',
    right: 12,
    top: 16,
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    minWidth: 44,
    height: 42,
    borderRadius: 16,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#dbe7ff',
  },
  iconButtonText: {
    color: palette.primary,
    fontWeight: '900',
    fontSize: 13,
  },
  welcome: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  hero: {
    backgroundColor: palette.primaryDark,
    borderRadius: 32,
    padding: spacing.xl,
    minHeight: 352,
    justifyContent: 'flex-end',
    marginBottom: spacing.lg,
    ...shadowMedium,
  },
  eyebrow: {
    color: palette.primary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
  },
  heroTitle: {
    color: palette.white,
    fontSize: 38,
    lineHeight: 43,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 12,
  },
  heroText: {
    color: '#dbeafe',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginBottom: spacing.lg,
  },
  heroActions: {
    gap: 10,
  },
  sectionHeader: {
    marginBottom: 12,
    marginTop: spacing.sm,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.xs,
    fontWeight: '600',
  },
  pageIntro: {
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  pageTitle: {
    color: palette.text,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
    letterSpacing: 0,
  },
  pageText: {
    color: palette.textSecondary,
    fontSize: 16,
    lineHeight: 24,
    marginTop: spacing.xs,
    fontWeight: '600',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: spacing.lg,
  },
  categoryCard: {
    width: '47%',
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    minHeight: 116,
    justifyContent: 'space-between',
    ...shadowSoft,
  },
  categoryTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: '900',
  },
  categoryText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  ctaCard: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#c9d8ff',
    padding: spacing.lg,
    marginTop: spacing.sm,
  },
  ctaTitle: {
    color: palette.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    marginBottom: spacing.sm,
  },
  ctaText: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: spacing.md,
  },
  searchInput: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    paddingVertical: 15,
    fontSize: 16,
    color: palette.text,
    marginBottom: 12,
    ...shadowSoft,
  },
  marketplaceList: {
    flex: 1,
  },
  marketplaceContent: {
    paddingBottom: spacing.xl,
  },
  marketplaceHero: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  searchBar: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 24,
    minHeight: 58,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    ...shadowSoft,
  },
  searchIcon: {
    color: palette.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  searchField: {
    flex: 1,
    color: palette.text,
    fontSize: 16,
    fontWeight: '700',
    minHeight: 52,
  },
  clearButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f6ff',
  },
  clearButtonText: {
    color: palette.textSecondary,
    fontSize: 16,
    fontWeight: '900',
  },
  marketplaceToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginTop: spacing.md,
    marginBottom: spacing.md,
  },
  toolbarTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: '900',
  },
  toolbarCaption: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  refreshButton: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primaryDark,
  },
  refreshButtonText: {
    color: palette.white,
    fontSize: 18,
    fontWeight: '900',
  },
  filtersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  horizontalChips: {
    marginHorizontal: -spacing.md,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  filterChip: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  filterChipActive: {
    backgroundColor: palette.primaryDark,
    borderColor: palette.primaryDark,
  },
  filterChipText: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 13,
  },
  filterChipTextActive: {
    color: palette.white,
  },
  activeFiltersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: spacing.md,
  },
  activeFilterChip: {
    borderRadius: 999,
    backgroundColor: '#ecfdf3',
    borderWidth: 1,
    borderColor: '#abefc6',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  activeFilterText: {
    color: palette.success,
    fontSize: 12,
    fontWeight: '900',
  },
  filterPanel: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    gap: spacing.md,
    marginBottom: spacing.md,
    ...shadowSoft,
  },
  filterPanelTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: '900',
  },
  filterSectionLabel: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  miniInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 12,
    color: palette.text,
    fontSize: 15,
    fontWeight: '700',
  },
  professionalCard: {
    backgroundColor: palette.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: spacing.md,
    overflow: 'hidden',
    ...shadowSoft,
  },
  cardImage: {
    height: 156,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#eaf1ff',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  imagePlaceholderIcon: {
    color: palette.primary,
    fontSize: 30,
    fontWeight: '900',
  },
  imagePlaceholderText: {
    color: palette.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  cardImageFill: {
    width: '100%',
    height: '100%',
  },
  cardImageText: {
    color: palette.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  cardContent: {
    padding: spacing.md,
    gap: 10,
  },
  cardFooterAction: {
    color: palette.primary,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  professionalName: {
    color: palette.text,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    flex: 1,
  },
  professionalRole: {
    color: palette.primary,
    fontSize: 15,
    fontWeight: '900',
  },
  bodyText: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '600',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  metaText: {
    color: '#475467',
    fontSize: 13,
    fontWeight: '800',
  },
  availability: {
    color: palette.success,
    fontSize: 13,
    fontWeight: '900',
  },
  authCard: {
    backgroundColor: palette.surface,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.lg,
    ...shadowSoft,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    marginBottom: 14,
    ...shadowSoft,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
    letterSpacing: 0,
  },
  cardSubtitle: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginTop: spacing.sm,
  },
  formStack: {
    marginTop: spacing.md,
    gap: 14,
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 14,
    color: palette.text,
    fontSize: 16,
  },
  inputError: {
    borderColor: palette.error,
    backgroundColor: '#fff7f5',
  },
  fieldError: {
    color: palette.error,
    fontSize: 12,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: palette.primary,
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    ...shadowSoft,
  },
  primaryButtonText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  ghostButton: {
    backgroundColor: palette.surface,
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: palette.border,
  },
  ghostButtonText: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
  },
  disabled: {
    opacity: 0.55,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  segmented: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segment: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#f2f6ff',
    borderWidth: 1,
    borderColor: palette.border,
  },
  segmentActive: {
    backgroundColor: palette.primaryDark,
    borderColor: palette.primaryDark,
  },
  segmentText: {
    color: palette.textSecondary,
    fontWeight: '900',
    fontSize: 13,
  },
  segmentTextActive: {
    color: palette.white,
  },
  badge: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: palette.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  profileHero: {
    backgroundColor: palette.primaryDark,
    borderRadius: 32,
    padding: spacing.lg,
    alignItems: 'center',
    marginBottom: spacing.md,
    ...shadowMedium,
  },
  avatarLarge: {
    width: 96,
    height: 96,
    borderRadius: 34,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  avatarText: {
    color: palette.primary,
    fontSize: 30,
    fontWeight: '900',
  },
  profileAvatarFrame: {
    width: 104,
    height: 104,
    borderRadius: 36,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.55)',
  },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileName: {
    color: palette.white,
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  profileRole: {
    color: '#dbeafe',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  profileEmail: {
    color: '#dbeafe',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: -8,
    marginBottom: 12,
  },
  profileCompletion: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  profileCompletionText: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '900',
  },
  profileSectionCard: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 24,
    padding: spacing.md,
    gap: spacing.md,
    ...shadowSoft,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  profileRowIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceAlt,
  },
  profileRowIconText: {
    color: palette.primary,
  },
  profileRowBody: {
    flex: 1,
    minWidth: 0,
  },
  profileRowLabel: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  profileRowValue: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
    marginTop: 2,
  },
  profileAction: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    ...shadowSoft,
  },
  profileActionDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fff7f7',
  },
  profileActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceAlt,
  },
  profileActionIconDanger: {
    backgroundColor: '#fee4e2',
  },
  profileActionIconText: {
    color: palette.primary,
  },
  profileActionIconTextDanger: {
    color: palette.error,
  },
  profileActionBody: {
    flex: 1,
    minWidth: 0,
  },
  profileActionTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
  },
  profileActionTitleDanger: {
    color: palette.error,
  },
  profileActionText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: 2,
  },
  advancedPanel: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: spacing.md,
    gap: spacing.md,
  },
  pricePanel: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 20,
    padding: spacing.md,
    marginTop: 14,
  },
  priceLabel: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  priceText: {
    color: palette.text,
    fontSize: 24,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  dashboardHero: {
    backgroundColor: palette.surface,
    borderRadius: 30,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 14,
    ...shadowSoft,
  },
  dashboardStack: {
    gap: spacing.md,
  },
  roleHeroClient: {
    backgroundColor: palette.primaryDark,
    borderRadius: 30,
    padding: spacing.lg,
    gap: spacing.md,
    ...shadowMedium,
  },
  roleHeroProvider: {
    backgroundColor: '#0f766e',
    borderRadius: 30,
    padding: spacing.lg,
    gap: spacing.md,
    ...shadowMedium,
  },
  roleHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  roleHeaderText: {
    flex: 1,
  },
  roleAvatar: {
    width: 58,
    height: 58,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  roleAvatarAlt: {
    width: 58,
    height: 58,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  roleAvatarText: {
    color: palette.white,
    fontSize: 24,
    fontWeight: '900',
  },
  roleAvatarTextAlt: {
    color: palette.white,
    fontSize: 24,
    fontWeight: '900',
  },
  roleTitle: {
    color: palette.white,
    fontSize: 26,
    lineHeight: 31,
    fontWeight: '900',
  },
  roleSubtitle: {
    color: '#dbeafe',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginTop: spacing.xs,
  },
  primaryDashboardAction: {
    backgroundColor: palette.white,
    borderRadius: 22,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  primaryDashboardActionAlt: {
    backgroundColor: palette.white,
    borderRadius: 22,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  primaryDashboardTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
  },
  primaryDashboardText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: spacing.xs,
    maxWidth: 230,
  },
  primaryDashboardIcon: {
    color: palette.primary,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  metricCard: {
    flexGrow: 1,
    flexBasis: 104,
    minHeight: 104,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: spacing.md,
    justifyContent: 'space-between',
    ...shadowSoft,
  },
  metricValue: {
    color: palette.primaryDark,
    fontSize: 28,
    fontWeight: '900',
  },
  metricLabel: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  sectionBlock: {
    gap: spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  dashboardSectionTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: '900',
  },
  dashboardSectionCaption: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: 2,
  },
  dashboardActionList: {
    gap: spacing.sm,
  },
  dashboardAction: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    ...shadowSoft,
  },
  dashboardActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceAlt,
  },
  dashboardActionIconAlt: {
    width: 44,
    height: 44,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ccfbf1',
  },
  dashboardActionIconText: {
    color: palette.primary,
  },
  dashboardActionIconTextAlt: {
    color: '#0f766e',
  },
  dashboardActionBody: {
    flex: 1,
  },
  dashboardActionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  dashboardActionTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
    flex: 1,
  },
  dashboardActionText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: 2,
  },
  dashboardChevron: {
    color: palette.textMuted,
  },
  compactListItem: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 20,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    ...shadowSoft,
  },
  compactIcon: {
    width: 40,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceAlt,
  },
  compactIconAlt: {
    width: 40,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ccfbf1',
  },
  compactIconText: {
    color: palette.primary,
  },
  compactIconTextAlt: {
    color: '#0f766e',
  },
  compactItemBody: {
    flex: 1,
    minWidth: 0,
  },
  compactItemTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '900',
  },
  compactItemText: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 2,
  },
  requestsHero: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 26,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadowSoft,
  },
  requestsSummaryRow: {
    marginBottom: spacing.md,
  },
  requestCard: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 24,
    padding: spacing.md,
    gap: spacing.md,
    marginBottom: spacing.md,
    ...shadowSoft,
  },
  requestTitle: {
    color: palette.text,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
  },
  requestMessage: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: palette.primaryDark,
    borderRadius: 22,
    padding: spacing.md,
    minHeight: 104,
    justifyContent: 'space-between',
  },
  statValue: {
    color: palette.white,
    fontSize: 28,
    fontWeight: '900',
  },
  statLabel: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '800',
  },
  actionGrid: {
    gap: 12,
  },
  actionCard: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 24,
    padding: spacing.md,
    gap: 8,
    ...shadowSoft,
  },
  linkText: {
    color: palette.primary,
    fontSize: 14,
    fontWeight: '900',
  },
  notice: {
    backgroundColor: '#fffaeb',
    borderWidth: 1,
    borderColor: '#fedf89',
    borderRadius: 18,
    padding: 13,
    marginBottom: 12,
  },
  noticeText: {
    color: '#93370d',
    fontWeight: '800',
    lineHeight: 20,
  },
  loadingPill: {
    backgroundColor: palette.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingText: {
    color: palette.textSecondary,
    fontWeight: '800',
  },
  skeletonCard: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.md,
    gap: 12,
    marginBottom: spacing.md,
  },
  skeletonBlock: {
    height: 16,
    borderRadius: 999,
    backgroundColor: '#e8eef8',
  },
  skeletonMedia: {
    height: 132,
    borderRadius: 20,
    backgroundColor: '#e8eef8',
  },
  emptyState: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: spacing.lg,
    alignItems: 'center',
    gap: 8,
    ...shadowSoft,
  },
  emptyIcon: {
    width: 54,
    height: 54,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceAlt,
    marginBottom: 4,
  },
  emptyIconText: {
    color: palette.primary,
    fontSize: 24,
    fontWeight: '900',
  },
  emptyTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: palette.textSecondary,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  tipBox: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#c9d8ff',
  },
  tipBoxMuted: {
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
  },
  tipTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: spacing.xs,
  },
  tipText: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  tabBarShell: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderWidth: 1,
    borderColor: 'rgba(217,226,241,0.95)',
    paddingHorizontal: 8,
    paddingTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    ...shadowMedium,
  },
  tabButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  tabButtonActive: {
    backgroundColor: palette.primaryDark,
  },
  tabIcon: {
    fontSize: 19,
    fontWeight: '900',
    color: palette.textMuted,
  },
  tabIconActive: {
    color: palette.white,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '900',
    color: palette.textMuted,
  },
  tabLabelActive: {
    color: palette.white,
  },
});
